# Services used externally
---
apiVersion: v1
kind: Service
metadata:
  name: memcached
spec:
  ports:
  - name: memcached
    port: 11211
  selector:
    app: memcached
---
apiVersion: v1
kind: Service
metadata:
  name: beanstalkd
spec:
  ports:
  - name: beanstalkd
    port: 11300
  selector:
    app: beanstalkd
