# Sensitive environment variables
---
apiVersion: v1
stringData:
  # A good secret should be supplied here
  SECRET_KEY: secret-key

  DBPASSWORD: ganetimgr

  # Set the same secret as for go-novncauthproxy
  NOVNC_JWE_SECRET: 32bytes-encoded-in-base64
  # Specify VNC password deployed on ganeti cluster 
  #NOVNC_JWE_SERVER_PASSWORD: ''
kind: Secret
metadata:
  name: ganetimgr
